stages:
  - name: Codeception test
    steps:
    - runScriptConfig:
        image: php:7.2
        shellScript: |-
          apt-get update
          apt-get install -y --no-install-recommends git zip libsqlite3-dev zlib1g-dev
          docker-php-ext-install zip
          curl --silent --show-error https://getcomposer.org/installer | php
          ./composer.phar install -n --prefer-dist
          touch storage/testing.sqlite storage/database.sqlite
          cp .env.testing .env
          php artisan migrate
          php artisan migrate --env=testing --database=sqlite_testing --force
          ./vendor/bin/codecept build
          ./vendor/bin/codecept run
  - name: Publish laravel image
    steps:
    - publishImageConfig:
        dockerfilePath: ./Dockerfile
        buildContext: .
        tag: ${CICD_GIT_REPO_NAME}:${CICD_GIT_BRANCH}-${CICD_EXECUTION_SEQUENCE}
  - name: deploy ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH} environment
    steps:
    - applyYamlConfig:
        path: ./k8s-yaml/laravel-deployment.yaml
    - applyYamlConfig:
        path: ./k8s-yaml/laravel-service.yaml
