stages:
  - name: Publish laravel image
    steps:
    - publishImageConfig:
        dockerfilePath: ./Dockerfile
        setting: mtu: 1000
        buildContext: .
        tag: ${CICD_GIT_REPO_NAME}:${CICD_GIT_BRANCH}-${CICD_EXECUTION_SEQUENCE}
  - name: deploy ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH} environment
    steps:
    - applyYamlConfig:
        path: ./k8s-yaml/laravel-deployment.yaml
    - applyYamlConfig:
        path: ./k8s-yaml/laravel-service.yaml
